# fly.toml file generated for chess-game-server on 2023-09-23T15:08:34-05:00

app = "chess-game-server"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "bos"
processes = []

[env]
  PORT = "2567"

[[services]]
  internal_port = 2567
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25 
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
